;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; https://projecteuler.net/problem=2
;;
;;  Each new term in the Fibonacci sequence is generated by adding the previous
;;  two terms. By starting with 1 and 2, the first 10 terms will be:
;;    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;  By considering the terms in the Fibonacci sequence whose values do not
;;  exceed four million, find the sum of the even-valued terms.
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
#lang racket
(
(define (fib n)
  (cond [(= 1 n) '(1)]
        [(= 2 n) '(2 1)]
        [else (let ([fib-lst (fib (sub1 n))])
                (cons (+ (car fib-lst) (car (cdr fib-lst))) fib-lst))]))

;; TO FINISH
